import pandas as pd
import numpy as np
import sys
import requests
import urllib.parse

desired_width = 1000
pd.set_option('display.width', desired_width)
np.set_printoptions(linewidth=desired_width,threshold=sys.maxsize)
pd.set_option('display.max_columns', 35)

'''
query = "Viceroy's House"
print(urllib.parse.quote_plus(query))
'''

'''

def get_data_by_title(url):
    response = requests.request("GET", url)
    #df = pd.read_json(response.text)
    #print(df)
    print(response.text)

'''

global df_initial
df_initial = pd.read_json(r'C:\Users\Solomon\Desktop\Pyg Hack\JSON.py')
#url = "http://www.omdbapi.com/?t=Blaze&apikey=11e7d31d"


def get_data_by_title(url):
    response = requests.request("GET", url)
    df = pd.read_json(response.text)
    #ser = pd.read_json(response.text, typ='series')
    #df = ser.to_frame()
    global df_initial
    df_initial = pd.concat([df_initial,df])


#get_data_by_title("http://www.omdbapi.com/?t=2019 Oscar Nominated Short Films: Animation&apikey=11e7d31d")


get_data_by_title("http://www.omdbapi.com/?t=2019 Oscar Nominated Short Films: Animation&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Bread Factory, Part One&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Bread Factory, Part Two&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Faithful Man &apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Fantastic Woman&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Ghost Story&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Hard Day's Night&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A League of Their Own&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Man Called Ove&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Matter of Life and Death&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Quiet Passion&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A Quiet Place&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=A United Kingdom&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=After Auschwitz&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Akira&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ali: Fear Eats The Soul&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Alien&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Alive and Kicking&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=All Is True&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=All That Heaven Allows&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=All the Queen's Horses&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=All-Nite Horror Marathon V&apikey=11e7d31d")
#get_data_by_title("http://www.omdbapi.com/?t=Amadeus: The Director's Cut&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Amazing Grace&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=American Woman&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=An Evening With Linnea Quigley&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Ancien and the Magic Tablet&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Andrei Rublev&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Anna and the Apocalypse&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Annihilation&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Apollo 11&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Arrival&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ask Dr. Ruth&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=At Eternity's Gate&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Audition&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Batman: The Movie&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Beatriz at Dinner&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Before We Vanish&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Belladonna of Sadness&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Belle De Jour&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Beyond the Valley of the Dolls&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Bicycle Thieves&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Bike Movie Night&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Birds of Passage&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Bisbee '17&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Black Clover&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Black Girl&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=BlacKkKlansman&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Blade&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Blade Runner&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Blade Runner 2049&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Blaze&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Blindspotting&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Blockers&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Blue Collar&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Bombshell: The Hedy Lamarr Story&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Bones&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Booksmart&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Border&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Boyz n the Hood&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Brain Damage&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Brazil&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Burning&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Butch Cassidy and the Sundance Kid&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Buy Me a Gun&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Cafe Society&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Cairo in One Breath&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Can You Ever Forgive Me?&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Candyman&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Cape Fear&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Capernaum&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Carmen Jones&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Casablanca&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=CatVideoFest 2018&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Cemetery Without Crosses&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Certain Women&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Chavela&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Children of Men&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Christine&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Climax&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Close Encounters of the Third Kind&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Cold War&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Colossal&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Columbus&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Cooley High&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Crooklyn&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Damsel&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Darkest Hour&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Daughters of the Dust&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Dawn of the Dead&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Dawson City: Frozen Time&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Deconstructing the Beatles' Revolver&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Deconstructing the Beatles' Sgt. Pepper&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Deconstructing the Beatles' White Album&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Deconstructing the Beatles: 1963 Yeah! Yeah! Yeah!&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Deconstructing the Birth of the Beatles&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Deep Red&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Demon&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Denial&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Destroyer&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Dilili in Paris&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Dirty Dancing&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Disobedience&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Dolores&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Don’t Look Now&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Donnie Darko&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Don't Think Twice&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Dr. Jekyll and Mr. Hyde&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Dreaming of a Jewish Christmas&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Echo In The Canyon&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=El Mar La Mar&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Elle&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Empire of the Ants&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Endless Poetry&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Eraserhead&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ernest Scared Stupid&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Eugene Onegin&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ex Libris: The New York Public Library&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ex Machina&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Faces Places&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Fanny and Alexander&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Femme Frontera Filmmaker Showcase&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Film Stars Don't Die in Liverpool&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Filmworker&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=First Man&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=First Reformed&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Flashdance&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Flower and Sword&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Foreign Body&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=Found Footage Festival, Vol. 8&apikey=11e7d31d")
#get_data_by_title("http://www.omdbapi.com/?t=Found Footage Festival: Cherished Gems&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Frantz&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Free Solo&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Gadget Girls & ’63 Boycott w/ Risé Sanders-Weir & Gordon Quinn&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ganja & Hess&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Gattaca&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=George A. Romero Double Feature&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Get Out&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ghost Stories&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Giant Little Ones&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Gimme Danger&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Girlhood&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Grace Jones: Bloodlight and Bami&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Grease&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Gremlins&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Groundhog Day&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Hagazussa&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Hail Satan?&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Halloween (1978)&apikey=11e7d31d")
#get_data_by_title("http://www.omdbapi.com/?t=Halloween (2018)&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Happy Death Day&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Hard to Be a God&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Harvey&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Have a Nice Day&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Have A Nice Day (Hao ji le)&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Henry: Portrait of a Serial Killer&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Hereditary&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=High Life &apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Holiday Heart&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Hot Summer Nights&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Hotel by the River&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=How to Talk to Girls at Parties&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Hunt for the Wilderpeople&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=I Am Cuba&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=I Am Not a Witch&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=I Am Not Your Negro&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=I, Daniel Blake&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=I, Tonya&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=If Beale Street Could Talk&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=In the Fade&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Indiana Jones and the Last Crusade&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Indignation&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Isle of Dogs&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ixcanul&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Jackie&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Jaws: The Revenge&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Jimi Hendrix Electric Church&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Juliet, Naked&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Jurassic Park&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=K2 and the Invisible Footmen&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Kedi&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Keep Quiet&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Kiki's Delivery Service&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Killer of Sheep&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=L’Atalante&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Labyrinth&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Lady Bird&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Lady Macbeth&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Landline&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Late Night&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Lean on Pete&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Leaning Into the Wind: Andy Goldsworthy&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Lemon&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Let the Corpses Tan&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Life, Animated&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Lion&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Little Men&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Little Woods&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Liyana&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Lo and Behold: Reveries of the Connected World&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Lobster&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Logan&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Long Day's Journey Into Night&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Loving&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Loving Vincent&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Luce&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mad Max: Fury Road&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=Made In Cuba: Short Film Program&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Madeline's Madeline&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Maiden&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Manchester by the Sea&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mandy&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Maria by Callas&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Marjorie Prime&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Marlina the Murderer in Four Acts&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mary and the Witch's Flower&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mary Magdalene&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mary Queen of Scots&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Maximum Overdrive&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=McKellen: Playing the Part&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Meeting Gorbachev&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Meeting the Man: James Baldwin in Paris / Ornette: Made in America&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Menashe&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mi vida dentro&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mia Madre&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Midsommar&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Minding the Gap&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mirai&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Miss Sharon Jones!&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mississippi Masala&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Monrovia, Indiana&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Monterey Pop&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Monty Python and the Holy Grail&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Moonlight&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Morris from America&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mortal Kombat&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Moses and Aaron&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=Mountainfilm 2019&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Mr. Gaga&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Multiple Maniacs&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=My Cousin Rachel&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=My Neighbor Totoro&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Nancy&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=National Theatre Live: Follies&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=National Theatre Live: The Threepenny Opera&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=National Theatre Live: Yerma&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Nausicaä of the Valley of the Wind&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Night of the Living Dead&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Nise: The Heart of Madness&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=No Man's Land&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Non-Fiction &apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Norman&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Novitiate&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Obit.&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ocean Waves&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Oh Lucy!&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Okko’s Inn&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=On the Beach at Night Alone&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=One More Time with Feeling&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=One Week and a Day&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ophelia&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Paddington 2&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Pasolini&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Paterson&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Pavarotti&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Persona&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Pet Sematary&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Phantasm&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Phantom of the Paradise&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Phantom Thread&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Plus One&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Police Story&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Polyester &apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Possession&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Prom Night&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Punch-Drunk Love&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=R.S.&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Rafiki&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=RBG&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Red Joan&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Retablo&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Revenge&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Robot & Frank&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Rogers Park&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Rollerball&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Roma&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Rosa Chumbe&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Rosemary's Baby&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Rubber&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ruben Blades is Not My Name&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Ruben Brandt, Collector&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Santa Sangre&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Satan & Adam&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Saving Brinton&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Scarlet Diva&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Science Fair&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=Science on Screen: Bombshell: The Hedy Lamarr Story&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Selma&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=Sex Work Activism: Body Politics and Human Rights&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Shadow&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Shalom Bollywood: The Untold Story of Indian Cinema&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Shoplifters&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Silence&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Skate Kitchen&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Slice&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=Smart 'n Spooky Kids&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Solaris&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Sonita&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Sorry to Bother You&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Space is the Place&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Space Jam&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Speak Up&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Stalker&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Stan & Ollie&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Stefan Zweig: Farewell to Europe&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Step&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Stop Making Sense&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Studio 54&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Summer 1993&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Summer of 84&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Summer with Monika&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Superman&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=Suspiria (1977)&apikey=11e7d31d")
#get_data_by_title("http://www.omdbapi.com/?t=Suspiria (2018)&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Sword of Trust&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=T2 Trainspotting&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Tales From The Hood&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Tangerine&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Taxi Driver&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Tell Them We Are Rising: The Story of Black Colleges and Universities&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Terminal Island&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=The 18th Annual Animation Show of Shows&apikey=11e7d31d")
#get_data_by_title("http://www.omdbapi.com/?t=The 19th Annual Animation Show of Shows&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Aftermath&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Bad Batch&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Beaches of Agnès&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Beatles: Eight Days a Week - The Touring Years&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Beguiled&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The BFG&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=The Big Bad Fox and Other Tales…&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=The Big Lebowski&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Big Sick&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Biggest Little Farm&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Bird with the Crystal Plumage&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Black Cat&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=The Blob (1988)&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Book of Life&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Cakemaker&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Clan&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Clovehitch Killer&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Club&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Dead Don't Die&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Death of Stalin&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Endless&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Exorcist&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Farewell&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Favourite&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Florida Project&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Fog&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Friends of Eddie Coyle&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Gospel According to André&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Grand Budapest Hotel&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Guilty&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Handmaiden&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Handmaid's Tale&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Heiresses&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Hero&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Howling&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Innocents&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Insult&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Killing of a Sacred Deer&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Last Black Man in San Francisco&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Little Hours&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Lost City of Z&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Lovers&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Lure&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Man Who Killed Don Quixote&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Matrix&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Miseducation of Cameron Post&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Mulberry House&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Muppet Christmas Carol&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Night of the Hunter&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Nightingale&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=The Nutcracker (NYC Ballet)&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Nutty Professor&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Old Man & the Gun&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Ornithologist&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Oscar Nominated Short Films 2017: Animation&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Oscar Nominated Short Films 2017: Documentary&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Oscar Nominated Short Films 2017: Live Action&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Oscar Nominated Short Films 2018: Animation&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Oscar Nominated Short Films 2018: Documentary&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Oscar Nominated Short Films 2018: Live Action&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Oscar Nominated Short Films 2019: Documentary&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Oscar Nominated Short Films 2019: Live Action&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Party&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Passion of Joan of Arc&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The People vs. Fritz Bauer&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The River and the Wall&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Rocky Horror Picture Show&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Room&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Salesman&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Sandlot&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Second Mother&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Shape of Water&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Texas Chain Saw Massacre&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Texas Chainsaw Massacre 2&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Treasure of the Sierra Madre&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Trip to Spain&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Umbrellas of Cherbourg&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The United States of Autism&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Vessel&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Void&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Wailing&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Wife&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Wound&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=The Zookeeper's Wife&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Thelma & Louise&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=They Shall Not Grow Old&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=This Is Home: A Refugee Story&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Thoroughbreds&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Three BIllboards Outside Ebbing, Missouri&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Three Identical Strangers&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Tickled&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Time for Ilhan&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Tito and the Birds&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=To Be Or Not to Be&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Todo el año es navidad&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Tom of Finland&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Tommy&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Toni Erdmann&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Toni Morrison: The Pieces I am &apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Tony Conrad: Completely in the Present&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Too Late to Die Young &apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Transit&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Truth or Dare&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Twin Peaks: Fire Walk with Me &apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Twister&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Velvet Goldmine&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Viceroy's House&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Victoria and Abdul&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Weiner&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Wendy and Lucy&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=What Ever Happened to Baby Jane?&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Whose Streets?&apikey=11e7d31d")

#get_data_by_title("http://www.omdbapi.com/?t=Why Don’t You Play in Hell?&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Wild & Scenic Film Festival 2017&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Wild Nights with Emily&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Wildlife&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Willy Wonka & the Chocolate Factory&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Woman at War&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Won't You Be My Neighbor?&apikey=11e7d31d")

get_data_by_title("http://www.omdbapi.com/?t=Yellow Submarine&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=You Were Never Really Here&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Your Name.&apikey=11e7d31d")
get_data_by_title("http://www.omdbapi.com/?t=Zama&apikey=11e7d31d")


#get_data_by_title("http://www.omdbapi.com/?t=The Gospel According to André&apikey=11e7d31d")
#get_data_by_title("http://www.omdbapi.com/?t=Arrival&apikey=11e7d31d")

print(df_initial)
df_initial.to_csv(r'C:\Users\Solomon\Desktop\movie_with_data_API.csv')

'''
url = "https://movie-database-imdb-alternative.p.rapidapi.com/"

querystring = {"page":"1","r":"json","s":"The Lovers"}

headers = {
    'x-rapidapi-host': "movie-database-imdb-alternative.p.rapidapi.com",
    'x-rapidapi-key': "7a74a7fff7mshcd10438e32c455ap11897fjsnbb321ee4d3da"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

print(response.text)

'''

df_movie_data_kaggle = pd.read_csv(filepath_or_buffer = r'C:\Users\Solomon\Desktop\Pyg Hack\the_movies_dataset\movies_metadata.csv')
df_pyg_event_sales = pd.read_csv(r'C:\Users\Solomon\Desktop\Pyg Hack\PygArtHackTheater2019\datasets\gross_revenue_by_event.csv', encoding='cp1252')
df = df_movie_data_kaggle.set_index('original_title').join(df_pyg_event_sales.set_index('original_title'))
df = df.dropna(subset=['Gross Revenue'])

#df.to_csv(r'C:\Users\Solomon\Desktop\movie_with_data.csv')
#print(df)


df_movie_data_DW = pd.read_csv(filepath_or_buffer = r'C:\Users\Solomon\Desktop\Pyg Hack\movie_metadata.csv')
df_pyg_event_sales = pd.read_csv(r'C:\Users\Solomon\Desktop\Pyg Hack\PygArtHackTheater2019\datasets\gross_revenue_by_event.csv', encoding='cp1252')
df = df_movie_data_DW.set_index('original_title').join(df_pyg_event_sales.set_index('original_title'))
df = df.dropna(subset=['Gross Revenue'])

#df.to_csv(r'C:\Users\Solomon\Desktop\movie_with_data_new.csv')
#print(df)
#tp = pd.read_csv(r'C:\Users\Solomon\Desktop\Pyg Hack\name.basics.tsv\data.tsv',sep='\t', header=None, chunksize=1000)
#df = pd.concat(tp, ignore_index=True)







